// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_dC5CJkuegjOt3nepvCi_6YSpJxMB7G0',
    appId: '1:502456624725:web:68babcb8cfa589436756dc',
    messagingSenderId: '502456624725',
    projectId: 'chatflutter-cft',
    authDomain: 'chatflutter-cft.firebaseapp.com',
    storageBucket: 'chatflutter-cft.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZQOeOdX1A0jedeyGbJlypXUlfLea79cw',
    appId: '1:502456624725:android:1ab0a90e901194c66756dc',
    messagingSenderId: '502456624725',
    projectId: 'chatflutter-cft',
    storageBucket: 'chatflutter-cft.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd6AP04tHLndUiI82LfYYdSuh88_vobf4',
    appId: '1:502456624725:ios:38b34f111338f3d76756dc',
    messagingSenderId: '502456624725',
    projectId: 'chatflutter-cft',
    storageBucket: 'chatflutter-cft.appspot.com',
    iosClientId: '502456624725-3r757osu2fkjoms2en2087p49rojc48d.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd6AP04tHLndUiI82LfYYdSuh88_vobf4',
    appId: '1:502456624725:ios:5982f6e0e989a7866756dc',
    messagingSenderId: '502456624725',
    projectId: 'chatflutter-cft',
    storageBucket: 'chatflutter-cft.appspot.com',
    iosClientId: '502456624725-7hts5co9gnuh8rh2mae3rdehr29k7kt6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatflutter.RunnerTests',
  );
}
